import Navbar from "@/components/Navbar"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Sidebar from "@/components/Sidebar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Whatsapp Gateway",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="drawer lg:drawer-open">
          <input id="my-drawer-3" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content flex flex-col bg-base-100">
            <Navbar />
            <div className="m-10">
              <div className="flex justify-between items-center border-b p-4 bg-base-100 rounded">
                <h1 className="prose prose-xl font-bold">Dashboard</h1>
                <div className="text-sm breadcrumbs">
                  <ul>
                    <li>
                      <a>Home</a>
                    </li>
                    <li>
                      <a>Documents</a>
                    </li>
                    <li>Add Document</li>
                  </ul>
                </div>
              </div>
              <div className="mt-5 bg-base-100 p-4 rounded">{children}</div>
            </div>
            <footer className="footer footer-center p-4 bg-neutral text-neutral-content">
              <div className="">
                <p>Copyright © {(new Date()).getFullYear()} - All right reserved by Ashary Vermaysha.</p>
              </div>
            </footer>
          </div>
          <div className="drawer-side w-screen">
            <label htmlFor="my-drawer-3" className="drawer-overlay" />
            <Sidebar />
          </div>
        </div>
      </body>
    </html>
  )
}
